local home = os.getenv 'HOME'

return {
  {
    name = 'trt_llm',
    local_prefix = home .. '/work',
    root_name_pattern = '^trt%-llm',
    remote_prefix = '/workspace',
    rexec_pod = 'clangd',
    ssh_alias = 'baseten-remote-clangd-pod',
    clangd = 'clangd-18',
    compiler = 'clang++-18',
    cuda_arch = 'sm_100a',
    cuda_path = '/usr/local/cuda',
    cmake = {
      source_dir = 'cpp',
      environment = {
        OPAL_PREFIX = '/opt/hpcx/ompi',
      },
      args = {
        '-G',
        'Ninja',
        '-DCMAKE_BUILD_TYPE=Release',
        '-DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc',
        '-DCMAKE_CUDA_ARCHITECTURES=100-real',
        '-DMPI_C_COMPILER=/opt/hpcx/ompi/bin/mpicc',
        '-DMPI_CXX_COMPILER=/opt/hpcx/ompi/bin/mpicxx',
        '-DPython_EXECUTABLE=/usr/bin/python3',
        '-DPython3_EXECUTABLE=/usr/bin/python3',
        '-DTensorRT_ROOT=/usr/local/tensorrt',
        '-DTRTLLM_FETCHCONTENT_CACHE=/tmp/remote-clangd/fetchcontent-cache',
        '-DBUILD_PYT=ON',
        '-DBUILD_TESTS=OFF',
        '-DBUILD_BENCHMARKS=OFF',
        '-DBUILD_DEEP_EP=OFF',
        '-DBUILD_DEEP_GEMM=OFF',
        '-DBUILD_FLASH_MLA=OFF',
        '-DBUILD_MICRO_BENCHMARKS=OFF',
      },
    },
    filetypes = { 'c', 'cpp', 'cuda' },
    preflight = true,
  },
  {
    name = 'b200',
    local_prefix = home .. '/work',
    remote_prefix = '/workspace',
    rexec_pod = 'clangd',
    ssh_alias = 'baseten-remote-clangd-pod',
    clangd = 'clangd-18',
    compiler = 'clang++-18',
    cuda_arch = 'sm_100a',
    cuda_path = '/usr/local/cuda',
    filetypes = { 'cuda' },
    preflight = true,
  },
}
